theme: jekyll-theme-cayman
title: Gemstone.Numeric
description: GPA Gemstone Numeric Library
github:
  repository_name: Gemstone.Numeric
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji